### PR TITLE
Fix bug where fact(0) was returning 0 instead of 1.

### LINKED ISSUE #382: spire.math.fact(0) == 0
shouldn't this evaluate to 1 instead of 0?

### PR DESCRIPTION
**Pull request by non**
This fixes #382.

### CODE REVIEW

**Comment by tixxit** [comment]
We should probably add a test for this too.

**Comment by non** [comment]
Yes, that's a great point.

**Comment by non** [comment]
(That previous test failure was the intermittent *float gcd* error, by the way.)

**Comment by non** [comment]
Alright tests added and passed. Thanks @jinmago for catching this!

**Pull request merged**
