### PR TITLE
Upgrade minor versions of sbt, scala and libraryDependencies

### PR DESCRIPTION
**Pull request by seratch**
This pull request upgrades minor versions of sbt, scala and libraryDependencies. 
I've checked dependencies' latest versions by using [sbt-updates](https://github.com/rtimush/sbt-updates).

- Bump sbt 0.13.7 to 0.13.8
- Bump Scala minor versions (also Travis settings)
- Bump scalatest, scalacheck, caliper stuff and so on
- Bump sbt-pgp 0.8 to 1.0.0 (I'm already heavily using in my projects)

### CODE REVIEW

**Comment by non** [comment]
Seems like a transient build error. I'm re-running, will merge if it passes.

Thanks!

**Comment by non** [comment]
It seems like the build keeps stalling and getting killed by Travis.

Have you completed a clean build? Any sense of how long you expect it to take? It's possible one of these upgrades extended the duration in 2.10 until the build doesn't finish on time.

**Comment by seratch** [comment]
I just tried `sbt ++2.10.5 clean test` again and that successfully finished in 493 seconds on my machine. Would you rerun the Travis job?

**Comment by non** [comment]
So at this point I've run the build 4-5 times and it's failed every time.

It seems like we're just exceeding Travis' maximum time allowed without output.

**Comment by non** [comment]
I'll try to look into possible ways to speed up the build under 2.10. I'm nervous about giving up on 2.10 in Travis, since it has caught real compatibility bugs. I guess we'll see.

**Comment by seratch** [comment]
Thanks. After doing `rm -rf */target`, this problem represented on my machine too. I'll investigate more on that.

**Comment by non** [comment]
Hey there,

Sorry to possibly conflict with you on #419 -- this was something I was working on before this PR came in. If that gets merged I can try to help update this PR to get it merged as well.

**Comment by seratch** [comment]
just rebased against the master branch although I've not fixed the Scala 2.10 build issue yet..

**Comment by non** [comment]
In the short term, you might want to try reverting to 2.10.2 and see if the rest of it works.

We chose not to upgrade to 2.10.3 or 2.10.4 because the compile times were way too slow, and there weren't any obvious problems we noticed with 2.10.2. So I'd be fine with leaving it back here as well.

**Comment by seratch** [comment]
Thanks. I just reverted Scala 2.10 minor version and Travis build looks fine. https://github.com/seratch/spire/commit/7df155e1c1a254f7f5d4c3984347005db8fdb35a

**Comment by non** [comment]
Merging. Thanks!

**Pull request merged**
