### PR TITLE
be Scala 2.13 friendly

### PR DESCRIPTION
**Pull request by SethTisue**
for the Scala 2.13 community build (yes, there is one already)

### CODE REVIEW

**Comment by SethTisue** [comment]
hi, is there someone who could review/merge this? it would be convenient to have it merged because then I don't have to work around it in the scala/community-builds repo.

**Comment by denisrosset** [comment]
LGTM

**Comment by SethTisue** [comment]
thank you!

**Comment by SethTisue** [comment]
green again :-) https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/186/consoleFull

**Pull request merged**
