### PR TITLE
Rational muldiv fastpath

### PR DESCRIPTION
**Pull request by rklaehn**

### CODE REVIEW

**Comment by rklaehn** [comment]
This is an attempt to add a "fast path" for multiplication and division for when both the arguments and the result are within the range of LongRational. In my benchmarks it improves the performance of common operations (multiply by integer, multiply by small rational) quite a bit, while having only a very small negative performance impact when the result or one of the intermediate results exceeds the range of long. For benchmark results, see below.

The only case that is negatively affected is the "medium" case, where both arguments are LongRational, but the result is BigRational. But as you can see the downside is not that large.

However, this is a larger change than the ones I have done before, so I think it would be good to have a thorough review.

Note that this would take care of #376 as well, since if you remain in the default branch of checked you know that the result must be a LongRational, and you can also easily ensure that the denominator is positive. So you can directly call the apply method of LongRational.

Here is the benchmark code for *. I try to cover all cases.
```scala
import ichi.bench.Thyme
import spire.math.Rational

object RationalProductBench extends App {
  val th = Thyme.warmed(warmth = Thyme.HowWarm.Bench, verbose = println)
  def bench(title:String, a:Rational, b:Rational) : Unit = {
    println(s"Rational product benchmark $title ${a.getClass.getSimpleName}($a) ${b.getClass.getSimpleName}($b)")
    th.pbenchWarm(th.Warm(a * b), title = "*")
  }
  bench("Integer", Rational(12345), Rational(67890))
  bench("LeftInteger", Rational(12345), Rational(67890,12347))
  bench("RightInteger", Rational(12345,67891), Rational(67890))
  bench("Small", Rational(12345,67891), Rational(67890,12347))
  bench("Medium", Rational(Long.MaxValue,Int.MaxValue - 1), Rational(Long.MaxValue,Int.MaxValue - 3))
  bench("Large", Rational(Long.MaxValue) + Rational(1,3), Rational(Long.MaxValue) + Rational(1,5))
}
```

Here are the results on this branch:
```
Rational product benchmark Integer LongRational(12345) LongRational(67890)
Benchmark for * (140 calls in 2.064 s)
  Time:    27.79 ns   95% CI 26.46 ns - 29.13 ns   (n=20)
  Garbage: 0.2384 ns   (n=4 sweeps measured)
Rational product benchmark LeftInteger LongRational(12345) LongRational(67890/12347)
Benchmark for * (140 calls in 2.703 s)
  Time:    73.35 ns   95% CI 70.30 ns - 76.40 ns   (n=20)
  Garbage: 0.3338 ns   (n=2 sweeps measured)
Rational product benchmark RightInteger LongRational(12345/67891) LongRational(67890)
Benchmark for * (140 calls in 3.194 s)
  Time:    83.06 ns   95% CI 80.06 ns - 86.05 ns   (n=20)
  Garbage: 0.2384 ns   (n=2 sweeps measured)
Rational product benchmark Small LongRational(12345/67891) LongRational(67890/12347)
Benchmark for * (60 calls in 1.444 s)
  Time:    90.91 ns   95% CI 86.03 ns - 95.80 ns   (n=20)
  Garbage: 0.2861 ns   (n=1 sweeps measured)
Rational product benchmark Medium LongRational(1317624576693539401/306783378) LongRational(9223372036854775807/2147483644)
Benchmark for * (140 calls in 3.132 s)
  Time:    661.7 ns   95% CI 641.5 ns - 681.8 ns   (n=20)
  Garbage: 6.485 ns   (n=7 sweeps measured)
Rational product benchmark Large BigRational(27670116110564327422/3) BigRational(46116860184273879036/5)
Benchmark for * (140 calls in 2.108 s)
  Time:    901.6 ns   95% CI 858.2 ns - 945.0 ns   (n=20)
  Garbage: 10.68 ns   (n=6 sweeps measured)
```

And here is the same benchmark with the current version from maven (0.9.1):
```
Rational product benchmark Integer LongRational(12345) LongRational(67890)
Benchmark for * (140 calls in 2.522 s)
  Time:    130.4 ns   95% CI 125.7 ns - 135.1 ns   (n=19)
  Garbage: 1.335 ns   (n=6 sweeps measured)
Rational product benchmark LeftInteger LongRational(12345) LongRational(67890/12347)
Benchmark for * (60 calls in 1.108 s)
  Time:    139.4 ns   95% CI 131.3 ns - 147.4 ns   (n=20)
  Garbage: 1.907 ns   (n=3 sweeps measured)
Rational product benchmark RightInteger LongRational(12345/67891) LongRational(67890)
Benchmark for * (140 calls in 2.794 s)
  Time:    150.8 ns   95% CI 144.9 ns - 156.7 ns   (n=20)
  Garbage: 2.098 ns   (n=7 sweeps measured)
Rational product benchmark Small LongRational(12345/67891) LongRational(67890/12347)
Benchmark for * (140 calls in 2.960 s)
  Time:    157.5 ns   95% CI 152.1 ns - 163.0 ns   (n=19)
  Garbage: 1.240 ns   (n=6 sweeps measured)
Rational product benchmark Medium LongRational(1317624576693539401/306783378) LongRational(9223372036854775807/2147483644)
Benchmark for * (300 calls in 6.476 s)
  Time:    619.2 ns   95% CI 609.3 ns - 629.1 ns   (n=19)
  Garbage: 5.913 ns   (n=14 sweeps measured)
Rational product benchmark Large BigRational(27670116110564327422/3) BigRational(46116860184273879036/5)
Benchmark for * (60 calls in 1.762 s)
  Time:    878.1 ns   95% CI 838.4 ns - 917.7 ns   (n=20)
  Garbage: 9.918 ns   (n=6 sweeps measured)
```

Division is basically the same regarding the benchmarks, so I will omit the results to avoid exceeding the github post size limits... :-)

**Comment by rklaehn** [comment]
With the latest commit, the case where the result is a BigRational is much faster because we directly create a BigRational (we know that it isn't a LongRational because of the overflow).

**Comment by non** [comment]
Thanks! I don't think the extra check is controversial at all. Making the common cases fast is exactly what this type is supposed to do.

I'll review this and hopefully sign-off and merge today.

**Comment by rklaehn** [comment]
There is another branch that does the same for + and -: https://github.com/rklaehn/spire/tree/rational-sumdiff-fastpath . It depends on this branch to be merged, so I did not do a PR yet.

**Comment by non** [comment]
This seems great! :+1:

I'm merging this now. I will probably do some before-and-after profiling to verify your findings but I trust you on this and reading the code it seems better.

**Pull request merged**
