### PR TITLE
Bumped Scala, ScalaCheck version numbers.

### PR DESCRIPTION
**Pull request by denisrosset**
Scala -> 2.10.4 and 2.11.5
ScalaCheck -> 1.12.1

### CODE REVIEW

**Comment by tixxit** [comment]
The build failed with what look like legitimate scalacheck errors. We'll need to investigate/fix the bugs before we can merge.

**Comment by denisrosset** [comment]
@tixxit: look like problems with floating point number with extreme exponents (either very small or very large).

The GCD tests should only be applied on "nice" floating point numbers, or a more formal approach to the tests should be used, taking in account the properties of floating point algebras --- i.e. they are not associative, and so on.

```
[info] - Field syntax *** FAILED ***

[info] GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.

[info] (SyntaxTest.scala:65)

[info] Falsified after 50 successful property evaluations.

[info] Location: (SyntaxTest.scala:65)

[info] Occurred when passed generated values (

[info] arg0 = -1.7366180317157802E-150,

[info] arg1 = NonZero(1.23800183621889E-309)

[info] )
```

**Comment by tixxit** [comment]
I'm looking into this. The first problem I found in the `SyntaxTest` is with `lcm`. There is an underflow in `Double`'s `gcd`. It's returning 0, but the value is technically something close to 0, but not representable by `Double`, so I think that is OK. Not much we can do here, but this is exacerbated by `a % 0D` returning `NaN` which propagates out to `lcm`. This isn't really wrong (saying `lcm(a, 0D)` is `NaN`) though. So, now it is opinion time, do we

  1. Redefine `lcm(a, 0)` and `lcm(0, a)` to be 0, or
  2. Fix the test to compare `NaN`s as equal?

**Comment by denisrosset** [comment]
What about testing only nice `Double` values, with a special generator that would select number with an exponent between -10 et 10, _only for the gcd and lcm tests_ ?

**Comment by tixxit** [comment]
I could too, but I would still feel less guilty if I let ScalaCheck do its thing :) I've fixed the test by using `spire.optional.totalfloat._`. `GCDTest` errors are similar. I'll make a PR against your branch once I'm done.

**Comment by tixxit** [comment]
See https://github.com/denisrosset/spire/pull/1

**Comment by denisrosset** [comment]
Ow... Scala 2.10 complains.

```
[error] /home/travis/build/non/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: diverging implicit expansion for type Int(42) => ?{def +(x$1: ? >: A): ?}
[error] starting with method additiveSemigroupOps in trait AdditiveSemigroupSyntax
[error] ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[error] ^
[error] one error found
[error] (tests/test:compile) Compilation failed
[error] Total time: 422 s, completed Feb 2, 2015 1:29:32 PM
```

Actually, I've been having some implicit divergence errors with Int, for example when using `min` or `max`... how are we supposed to solve those ?

**Comment by denisrosset** [comment]
I ran `test:compile` with implicits logged, the problem is the following:
```
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqNormedVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqNormedVectorSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.algebra.NormedVectorSpace[CC[A(in method SeqNormedVectorSpace)],A(in method SeqNormedVectorSpace)]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqInnerProductSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqInnerProductSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqInnerProductSpace[A(in method SeqInnerProductSpace),CC[A(in method SeqInnerProductSpace)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqVectorSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqVectorSpace[A(in method SeqVectorSpace),CC[A(in method SeqVectorSpace)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqModule is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqModule), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqModule[A(in method SeqModule),CC[A(in method SeqModule)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqNormedVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqNormedVectorSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.algebra.NormedVectorSpace[CC[A(in method SeqNormedVectorSpace)],A(in method SeqNormedVectorSpace)]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqInnerProductSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqInnerProductSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqInnerProductSpace[A(in method SeqInnerProductSpace),CC[A(in method SeqInnerProductSpace)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqVectorSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqVectorSpace[A(in method SeqVectorSpace),CC[A(in method SeqVectorSpace)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqModule is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqModule), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqModule[A(in method SeqModule),CC[A(in method SeqModule)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: additiveSemigroupOps is not a valid implicit value for (=> a.type) => ?{def +: ?} because:
[info] incompatible: (a: A)(implicit evidence$8: spire.algebra.AdditiveSemigroup[A])spire.syntax.AdditiveSemigroupOps[A] does not match expected type (=> a.type) => ?{def +: ?}
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqNormedVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqNormedVectorSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.algebra.NormedVectorSpace[CC[A(in method SeqNormedVectorSpace)],A(in method SeqNormedVectorSpace)]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqInnerProductSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqInnerProductSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqInnerProductSpace[A(in method SeqInnerProductSpace),CC[A(in method SeqInnerProductSpace)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqVectorSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqVectorSpace[A(in method SeqVectorSpace),CC[A(in method SeqVectorSpace)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqModule is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqModule), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqModule[A(in method SeqModule),CC[A(in method SeqModule)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqNormedVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqNormedVectorSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.algebra.NormedVectorSpace[CC[A(in method SeqNormedVectorSpace)],A(in method SeqNormedVectorSpace)]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqInnerProductSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqInnerProductSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqInnerProductSpace[A(in method SeqInnerProductSpace),CC[A(in method SeqInnerProductSpace)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqVectorSpace), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqVectorSpace[A(in method SeqVectorSpace),CC[A(in method SeqVectorSpace)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqModule is not a valid implicit value for spire.algebra.AdditiveSemigroup[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqModule), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqModule[A(in method SeqModule),CC[A(in method SeqModule)]]
[info]  required: spire.algebra.AdditiveSemigroup[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqOrder is not a valid implicit value for spire.algebra.Eq[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqOrder), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqOrder[A(in method SeqOrder),CC[A(in method SeqOrder)]]
[info]  required: spire.algebra.Eq[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]           ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqEq is not a valid implicit value for spire.algebra.Eq[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqEq), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqEq[A(in method SeqEq),CC[A(in method SeqEq)]]
[info]  required: spire.algebra.Eq[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]           ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqOrder is not a valid implicit value for spire.algebra.Eq[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqOrder), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqOrder[A(in method SeqOrder),CC[A(in method SeqOrder)]]
[info]  required: spire.algebra.Eq[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]           ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:275: SeqEq is not a valid implicit value for spire.algebra.Eq[A] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [A(in method SeqEq), CC[A(in type CC)] <: scala.collection.SeqLike[A(in type CC),CC[A(in type CC)]]]spire.std.SeqEq[A(in method SeqEq),CC[A(in method SeqEq)]]
[info]  required: spire.algebra.Eq[A]
[info]       ((a + 42) === Ring[A].plus(a, Ring[A].fromInt(42))) &&
[info]           ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: SeqNormedVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[Any] because:
[info] hasMatchingSymbol reported error: ambiguous implicit values:
[info]  both value DoubleAlgebra in trait DoubleInstances of type => spire.std.DoubleAlgebra
[info]  and value evidence$27 of type spire.algebra.Field[A]
[info]  match expected type spire.algebra.Field[A]
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: SeqInnerProductSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[Any] because:
[info] hasMatchingSymbol reported error: ambiguous implicit values:
[info]  both value DoubleAlgebra in trait DoubleInstances of type => spire.std.DoubleAlgebra
[info]  and value evidence$27 of type spire.algebra.Field[A]
[info]  match expected type spire.algebra.Field[A]
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: SeqVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[Any] because:
[info] hasMatchingSymbol reported error: ambiguous implicit values:
[info]  both value DoubleAlgebra in trait DoubleInstances of type => spire.std.DoubleAlgebra
[info]  and value evidence$27 of type spire.algebra.Field[A]
[info]  match expected type spire.algebra.Field[A]
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: literalDoubleAdditiveSemigroupOps is not a valid implicit value for Int(42) => ?{def +(x$1: ? >: A): ?} because:
[info] diverging implicit expansion for type Int(42) => ?{def +(x$1: ? >: A): ?}
[info] starting with method additiveSemigroupOps in trait AdditiveSemigroupSyntax
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: literalLongAdditiveSemigroupOps is not a valid implicit value for Int(42) => ?{def +(x$1: ? >: A): ?} because:
[info] diverging implicit expansion for type Int(42) => ?{def +(x$1: ? >: A): ?}
[info] starting with method additiveSemigroupOps in trait AdditiveSemigroupSyntax
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: literalIntAdditiveSemigroupOps is not a valid implicit value for Int(42) => ?{def +(x$1: ? >: A): ?} because:
[info] diverging implicit expansion for type Int(42) => ?{def +(x$1: ? >: A): ?}
[info] starting with method additiveSemigroupOps in trait AdditiveSemigroupSyntax
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: SeqNormedVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[Any] because:
[info] hasMatchingSymbol reported error: ambiguous implicit values:
[info]  both value DoubleAlgebra in trait DoubleInstances of type => spire.std.DoubleAlgebra
[info]  and value evidence$27 of type spire.algebra.Field[A]
[info]  match expected type spire.algebra.Field[A]
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: SeqInnerProductSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[Any] because:
[info] hasMatchingSymbol reported error: ambiguous implicit values:
[info]  both value DoubleAlgebra in trait DoubleInstances of type => spire.std.DoubleAlgebra
[info]  and value evidence$27 of type spire.algebra.Field[A]
[info]  match expected type spire.algebra.Field[A]
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[info] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: SeqVectorSpace is not a valid implicit value for spire.algebra.AdditiveSemigroup[Any] because:
[info] hasMatchingSymbol reported error: ambiguous implicit values:
[info]  both value DoubleAlgebra in trait DoubleInstances of type => spire.std.DoubleAlgebra
[info]  and value evidence$27 of type spire.algebra.Field[A]
[info]  match expected type spire.algebra.Field[A]
[info]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[info]         ^
[error] /home/rossetd0/Documents/phd/libs/spire/tests/src/test/scala/spire/SyntaxTest.scala:276: diverging implicit expansion for type Int(42) => ?{def +(x$1: ? >: A): ?}
[error] starting with method additiveSemigroupOps in trait AdditiveSemigroupSyntax
[error]       ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
[error]         ^
```

**Comment by denisrosset** [comment]
@non and @tixxit: I need your help here; the compiler is looking for `spire.algebra.AdditiveSemigroup[Any]` in the cases where we add `i + a` where `i: Int` and `a: A` with an implicit `Field[A]`.

**Comment by denisrosset** [comment]
The problem was with the derivation of the Eq[A] type. I changed the affected lines from:

```scala
      ((42 + a) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
```
to
```
      (((42 + a): A) === Ring[A].plus(Ring[A].fromInt(42), a)) &&
```

and type inference works again correctly.

**Comment by denisrosset** [comment]
Still waiting for a :+1: to merge.

**Comment by denisrosset** [comment]
After reviewing this PR and the subsequent merge, can we perform a release of the current version ? I have a library with dependencies on partial algebras that I'd like to push on Sonatype.

**Comment by non** [comment]
Yes -- I think we have enough to do another release.

**Comment by non** [comment]
One thing about the `(a + 42)` versus `(42 + a)` issue -- there are implicits on literal `Int` values designed to make that machinery work with `Ring[A]`. See: https://github.com/non/spire/blob/master/core/src/main/scala/spire/syntax/Ops.scala#L168.

So... I'm not sure why the type annotation was necessary. I'd like to explore that before merging this if that's OK?

**Comment by denisrosset** [comment]
@non: I removed the explicit type annotation, and changed the order of tests. The compiler bug is then not triggered.

Waiting for the CI tests and your :+1: to merge.

**Comment by denisrosset** [comment]
Oh, and let's do the CI with the latest upstream merged.

**Comment by non** [comment]
OK, looks great, merging.

**Pull request merged**
