### PR TITLE
Added some tests to increase coverage of Rational

### PR DESCRIPTION
**Pull request by rklaehn**
Added some tests to increase coverage of Rational, and removed dead code that can not be tested because it is never called.

Also excluded the large piece of code for Rational.pow and Rational.nroot from coverage, because it is going to be removed soon anyway.

### CODE REVIEW

**Comment by non** [comment]
You mean `Rational#fpow` right? I think `Rational#pow` with an integer argument is definitely staying.

**Comment by rklaehn** [comment]
I mean this one:
```
def pow(exp: Rational)(implicit ctxt: ApproximationContext[Rational]): Rational
```

**Comment by non** [comment]
Oh yeah, that one will be going away.

**Comment by rklaehn** [comment]
By the way: the last commit is a fix for a completely trivial bug that I only discovered by mindlessly entering tests to get the coverage up. `Rational.apply(Rational.one: Number)` would result in infinite recursion. I think this underscores the need to increase test coverage to preferrably 100% even for seemingly trivial code.

The build failure is the float gcd thing.

**Comment by non** [comment]
Agreed. I'll merge this now if you are happy with it.

By the way, I'm close to 100% on `SafeLong`.

**Pull request merged**
