### PR TITLE
changed DoubleIsReal so that 'ceil' calls ceil instead of floor

### PR DESCRIPTION
**Pull request by bbuchsbaum**

### CODE REVIEW

**Comment by tixxit** [comment]
:+1: Should we check the rest of the code base for similar mistakes?

**Comment by tixxit** [comment]
Just, like, `ack --scala ceil.*floor` or something...

**Comment by adampingel** [comment]
The same issue is present in float.

A sequence of github button presses based on this PR resulted in the creation of a "Patch 1" PR: https://github.com/non/spire/pull/524

**Comment by adampingel** [comment]
My search I also found the RoundingMode in BigDecimalRootRefinement's floor method:
https://github.com/non/spire/blob/master/core/shared/src/main/scala/spire/math/poly/BigDecimalRootRefinement.scala#L139  (and also for ceil).

I may not understand the intent, but at first glance they appear to be swapped.

**Pull request merged**
