### PR TITLE
Microsite

### PR DESCRIPTION
**Pull request by denisrosset**
How to test locally:
- `sbt docs/makeMicrosite`
- `cd docs/target/site; jekyll serve`
- open http://127.0.0.1:4000/spire/

See #702

### CODE REVIEW

**Comment by denisrosset** [comment]
Thanks @larsrh ! Refreshing this right now.

**Comment by denisrosset** [comment]
@larsrh I reintegrated the unidoc keys, so the commented out code is running again.

As I'm not @non, a copy of the website can be consulted here:
http://denisrosset.github.io/spire/index.html

Remains to split the readme/guide into subpages, as in the cats documentation, but this is a good start already.

**Comment by larsrh** [comment]
@denisrosset Thanks for this! I'm happy for you to merge, but please squash-merge to avoid extra merge commits.

**Comment by denisrosset** [comment]
Closing as it is superceded.

**Pull request closed without merging**
