### PR TITLE
Differentiate Left and Right Modules

### PR DESCRIPTION
**Pull request by stephen-lazaro**
Resolves https://github.com/non/spire/issues/656.
I noticed there are no laws for module structures. Would adding them be wanted?

### CODE REVIEW

**Comment by denisrosset** [comment]
Hi @stephen-lazaro , welcome to Spire! I started digging into the module / vector space stuff, and it seems that what combines left+right modules is a commutative modules, which needs to be defined over a commutative ring.

What do you think?

**Comment by stephen-lazaro** [comment]
Thanks! Glad to be here.
Yep, for sure, though I believe in principle you can have bimodules over noncommutative rings. Perhaps the thing to do is additionally provide enforcement that all modules over Commutative rings are bimodules. I'll look into it.

**Comment by stephen-lazaro** [comment]
Woops, got carried away and pushed some broken things. Am resolving.
Overall, maybe something along these lines though? Distinguish modules as commutative, and bimodules as a feature available for possibly non-commutative rings.

**Comment by denisrosset** [comment]
Hi @stephen-lazaro, we did a sprint on the stale PR and issues with @non. I had some parallel on this subject in the experimental branch.

I restarted work on a different branch; we added you as a contributor in the authors file as you helped on this issue. Thanks for your contribution!

**Comment by stephen-lazaro** [comment]
Wow! Thanks. Glad it was helpful!

**Pull request closed without merging**
