### PR TITLE
Use SafeLong from Rational

### PR DESCRIPTION
**Pull request by rklaehn**
Now that we have improved SafeLong a bit, there is no reason we shouldn't use SafeLong as numerator and denominator. This has some performance advantages for small BigRationals that are just barely too big to fit into a long, and also has some storage size advantages for BigRationals where e.g. the denominator fits into a Long (most notably, large integers).

I ran SafeLong ring and Rational field tests 1000000 times to increase confidence that I introduced no new bugs.

Review by @non, @tixxit or @denisrosset 

I will post some benchmarks once they finished.

### CODE REVIEW

**Comment by tixxit** [comment]
Looks great! I'm looking forward to the benchmark results :)

**Comment by rklaehn** [comment]
New:
```
[info] Benchmark                                                        (kind)  Mode  Samples     Score  Score error  Units
[info] s.b.j.RationalAddSubtractBenchmark.difference                  li_li_li  avgt       10    36.586        1.737  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.difference                  bi_bi_bi  avgt       10   167.188        6.744  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.difference                  lf_lf_lf  avgt       10    82.626        5.676  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.difference                  lf_lf_bf  avgt       10   293.725        1.960  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.difference                  bf_bf_bf  avgt       10   209.305        5.531  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         li_li_li  avgt       10    36.407        1.696  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         bi_bi_bi  avgt       10   323.932       13.816  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         lf_lf_lf  avgt       10    79.416        1.657  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         lf_lf_bf  avgt       10   652.734       31.845  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         bf_bf_bf  avgt       10   370.089       16.530  ns/op
[info] s.b.j.RationalCompareBenchmark.compare                            li_li  avgt       10    23.046        0.679  ns/op
[info] s.b.j.RationalCompareBenchmark.compare                            lf_lf  avgt       10    23.606        1.109  ns/op
[info] s.b.j.RationalCompareBenchmark.compare            lf_lf_intermediateBig  avgt       10   118.966        3.462  ns/op
[info] s.b.j.RationalCompareBenchmark.compare                            bf_bf  avgt       10   116.379        4.770  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  li_li_li  avgt       10    29.388        1.211  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  bi_bi_bi  avgt       10   558.885       10.376  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  lf_lf_lf  avgt       10    86.325        5.308  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  lf_lf_bf  avgt       10   197.720        9.464  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  bf_bf_bf  avgt       10   661.921       33.795  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 li_li_li  avgt       10    71.210        3.158  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 bi_bi_bi  avgt       10  1671.362       54.805  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 lf_lf_lf  avgt       10    86.170        2.405  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 lf_lf_bf  avgt       10    83.832        2.670  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 bf_bf_bf  avgt       10  1725.042       57.007  ns/op
```

old
```
[info] Benchmark                                                        (kind)  Mode  Samples     Score  Score error  Units
[info] s.b.j.RationalAddSubtractBenchmark.difference                  li_li_li  avgt       10    36.103        2.324  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.difference                  bi_bi_bi  avgt       10   172.522        8.079  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.difference                  lf_lf_lf  avgt       10    85.845        3.426  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.difference                  lf_lf_bf  avgt       10   326.855        2.283  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.difference                  bf_bf_bf  avgt       10   234.224       14.716  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         li_li_li  avgt       10    34.455        1.322  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         bi_bi_bi  avgt       10   344.265       19.506  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         lf_lf_lf  avgt       10    83.135        5.217  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         lf_lf_bf  avgt       10   658.401        7.372  ns/op
[info] s.b.j.RationalAddSubtractBenchmark.sum                         bf_bf_bf  avgt       10   368.145        2.096  ns/op
[info] s.b.j.RationalCompareBenchmark.compare                            li_li  avgt       10    22.145        0.481  ns/op
[info] s.b.j.RationalCompareBenchmark.compare                            lf_lf  avgt       10    21.969        0.233  ns/op
[info] s.b.j.RationalCompareBenchmark.compare            lf_lf_intermediateBig  avgt       10   137.113        8.694  ns/op
[info] s.b.j.RationalCompareBenchmark.compare                            bf_bf  avgt       10   115.108        1.563  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  li_li_li  avgt       10    26.477        0.891  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  bi_bi_bi  avgt       10   618.087       28.761  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  lf_lf_lf  avgt       10    88.588        4.638  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  lf_lf_bf  avgt       10   207.295        7.199  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.product                  bf_bf_bf  avgt       10   706.613       32.790  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 li_li_li  avgt       10    72.130        2.605  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 bi_bi_bi  avgt       10  1609.971       79.248  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 lf_lf_lf  avgt       10    82.868        3.852  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 lf_lf_bf  avgt       10    82.600        4.194  ns/op
[info] s.b.j.RationalMultiplyDivideBenchmark.quotient                 bf_bf_bf  avgt       10  1671.426       35.994  ns/op
```

**Comment by rklaehn** [comment]
I ran sbt validateJVM a zillion times on this. I also ran the code below with 1000000 tests. I can't run validateJS locally because it produces an OOME GC overhead exceeded. Nevertheless I consider this validated.

```scala
object RationalProperties extends Properties("Rational") {
  for((name, prop) ← RingLaws[Rational].euclideanRing.all.properties)
    property(name) = prop
  for((name, prop) ← OrderLaws[Rational].order.all.properties)
    property(name) = prop
}

object SafeLongProperties extends Properties("SafeLong") {
  for((name, prop) ← RingLaws[SafeLong].ring.all.properties)
    property(name) = prop
  for((name, prop) ← OrderLaws[SafeLong].order.all.properties)
    property(name) = prop
}
```

**Comment by non** [comment]
Tests pass for me too. Looks great! Merging.

:rainbow: Thanks :rainbow:

**Pull request merged**
