### PR TITLE
Biased the interval test towards endpoints.

### PR DESCRIPTION
**Pull request by denisrosset**

### CODE REVIEW

**Comment by denisrosset** [comment]
I still get errors in `Interval`, and strengthened the tests by biasing the sampling towards the interval endpoints.

Examples below:

```
[info] - sampled binop * *** FAILED ***
[info]   TestFailedException was thrown during property evaluation.
[info]     Message: false was not equal to true
[info]     Location: (IntervalTest.scala:346)
[info]     Occurred when passed generated values (
[info]       arg0 = (720596098740629464/5150553020750929247, 3673345661590707614/3718518456232276325),
[info]       arg1 = [-6570477149428119191/2905429533408211707, 0]
[info]     )


[info] - sampled binop * *** FAILED ***
[info]   TestFailedException was thrown during property evaluation.
[info]     Message: false was not equal to true
[info]     Location: (IntervalTest.scala:346)
[info]     Occurred when passed generated values (
[info]       arg0 = [-9223372036854775808/9223372036854775807, 0],
[info]       arg1 = (-1066173871595804924, -1623009658433395662/1687398237624660433)
[info]     )
```

**Comment by denisrosset** [comment]
This is for `spire.math.IntervalCheck`

**Comment by denisrosset** [comment]
... and bug corrections.

The resulting code is quite ugly, but I don't see yet a nice refactoring for it...

**Comment by non** [comment]
Seems good to me.

I'd prefer correctness over beauty here. Thanks for looking into this!

**Pull request merged**
