### PR TITLE
Simplifies rational inheritance scheme

### PR DESCRIPTION
**Pull request by rklaehn**
This would be one step of #453 . I think it is preferable to merge this before attempting to do the other items of #453 . Especially 3) is pretty big.

I also made the constructors of SafeLongLong and SafeLongBigInt private[spire], since they allow breaking the invariant that SafeLongLong is always used for numbers that fit into a Long.

### CODE REVIEW

**Comment by non** [comment]
Looks good to me.

:+1:

**Comment by rklaehn** [comment]
OK, I will give @tixxit some time to review and then merge it.

**Comment by rklaehn** [comment]
@denisrosset does this look OK?

**Comment by denisrosset** [comment]
Perfect, thank you!

:+1:

**Comment by tixxit** [comment]
Post-merge, but :+1: :)

**Pull request merged**
