### PR TITLE
Implement Xorshift RNGs

### PR DESCRIPTION
**Pull request by andresilva**
This PR implements three variants of the Xorshift RNG [[1]](https://en.wikipedia.org/wiki/Xorshift).

### CODE REVIEW

**Comment by andrebeat** [comment]
I would also like to add these RNGs to the `RandomBenchmark` but unfortunately I'm unable to run any benchmark. 

```scala
[info] Running spire.benchmark.RandomBenchmarks
[error] Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.io.Closeables.closeQuietly(Ljava/io/Closeable;)V
[error]         at com.google.caliper.Runner.measure(Runner.java:299)
[error]         at com.google.caliper.Runner.runScenario(Runner.java:227)
[error]         at com.google.caliper.Runner.runOutOfProcess(Runner.java:376)
[error]         at com.google.caliper.Runner.run(Runner.java:95)
[error]         at com.google.caliper.Runner.main(Runner.java:421)
[error]         at com.google.caliper.Runner.main(Runner.java:433)
[error]         at spire.benchmark.MyRunner.main(Benchmark.scala:35)
[error]         at spire.benchmark.RandomBenchmarks.main(RandomBenchmark.scala)
[info]  0% Scenario{vm=java, trial=0, benchmark=NextIntJava}
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last benchmark/compile:run for the full output.
[error] (benchmark/compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 15 s, completed Jan 12, 2016 8:06:41 PM
```

**Comment by andrebeat** [comment]
I managed to run the benchmarks by downgrading the guava version from `18.0` to `15.0`. The results can be found [here](https://gist.github.com/andrebeat/4ab695dcb098c5ceac1f).

**Comment by rklaehn** [comment]
I don't have the time for a very detailed review. But from a glance this LGTM. @non WDYT?

**Comment by andrebeat** [comment]
I'm fine with letting this simmer for a while (maybe wait for the `spire-rand` module?). I haven't had the chance to read the XorShift papers yet [[1](http://www.jstatsoft.org/v08/i14/paper)] [[2](http://vigna.di.unimi.it/ftp/papers/xorshiftplus.pdf)] to make sure I'm not overlooking anything. I know that the choice of seed is very important for the performance of these RNGs. There's an implementation of XorShift RNGs in [dsi-utils](http://xorshift.di.unimi.it/) where they hash the provided seed (with MurmurHash) or use another RNG to generate the seed value.

**Comment by non** [comment]
I'm very sorry we let this linger for so long.

Overall it LGTM.

I'm planning on doing some updated RNG testing in the future (e.g. using the TestU01 rng testing suite). I'm happy to merge this for now and include it in our RNG testing in the future.

**Pull request merged**
